name: ci
on: [push, pull_request]

jobs:
  windows-msvc:
    runs-on: windows-latest
    defaults:
      run:
        shell: pwsh
    steps:
      - uses: actions/checkout@v4
  
      - name: Configure (Ninja, Release)
        run: cmake -S . -B build -G Ninja -DCMAKE_BUILD_TYPE=Release

      - name: Build
        run: cmake --build build -j

      - name: Run tests (ctest)
        run: ctest --test-dir build --output-on-failure